/* eslint-disable @typescript-eslint/no-explicit-any */
import type { AnimationPreset } from '../types/animation';

export const ANIMATION_PRESETS: any[] = [
  // === Einblenden ===
  {
    id: 'fadeIn',
    name: 'Einblenden',
    category: 'einblenden',
    effectType: 'fadeIn',
    keyframes: [
      { offset: 0, properties: { opacity: 0 } },
      { offset: 1, properties: { opacity: 1 } },
    ],
    defaultConfig: { duration: 0.6, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0 },
    motionAnimate: { opacity: 1 },
    motionTransition: { duration: 0.6, ease: 'easeOut' },
  },
  {
    id: 'blurIn',
    name: 'Weichzeichner',
    category: 'einblenden',
    effectType: 'blurIn',
    keyframes: [
      { offset: 0, properties: { opacity: 0, filter: 'blur(12px)' } },
      { offset: 1, properties: { opacity: 1, filter: 'blur(0px)' } },
    ],
    defaultConfig: { duration: 0.7, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, filter: 'blur(12px)' },
    motionAnimate: { opacity: 1, filter: 'blur(0px)' },
    motionTransition: { duration: 0.7, ease: 'easeOut' },
  },

  // === Bewegen ===
  {
    id: 'slideUp',
    name: 'Von unten',
    category: 'bewegen',
    effectType: 'slideUp',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'translateY(30px)' } },
      { offset: 1, properties: { opacity: 1, transform: 'translateY(0)' } },
    ],
    defaultConfig: { duration: 0.5, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, y: 30 },
    motionAnimate: { opacity: 1, y: 0 },
    motionTransition: { duration: 0.5, ease: 'easeOut' },
  },
  {
    id: 'slideDown',
    name: 'Von oben',
    category: 'bewegen',
    effectType: 'slideDown',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'translateY(-30px)' } },
      { offset: 1, properties: { opacity: 1, transform: 'translateY(0)' } },
    ],
    defaultConfig: { duration: 0.5, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, y: -30 },
    motionAnimate: { opacity: 1, y: 0 },
    motionTransition: { duration: 0.5, ease: 'easeOut' },
  },
  {
    id: 'slideLeft',
    name: 'Von rechts',
    category: 'bewegen',
    effectType: 'slideLeft',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'translateX(30px)' } },
      { offset: 1, properties: { opacity: 1, transform: 'translateX(0)' } },
    ],
    defaultConfig: { duration: 0.5, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, x: 30 },
    motionAnimate: { opacity: 1, x: 0 },
    motionTransition: { duration: 0.5, ease: 'easeOut' },
  },
  {
    id: 'slideRight',
    name: 'Von links',
    category: 'bewegen',
    effectType: 'slideRight',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'translateX(-30px)' } },
      { offset: 1, properties: { opacity: 1, transform: 'translateX(0)' } },
    ],
    defaultConfig: { duration: 0.5, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, x: -30 },
    motionAnimate: { opacity: 1, x: 0 },
    motionTransition: { duration: 0.5, ease: 'easeOut' },
  },

  // === Skalieren ===
  {
    id: 'scaleIn',
    name: 'Hereinzoomen',
    category: 'skalieren',
    effectType: 'scaleIn',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'scale(0.8)' } },
      { offset: 1, properties: { opacity: 1, transform: 'scale(1)' } },
    ],
    defaultConfig: { duration: 0.5, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, scale: 0.8 },
    motionAnimate: { opacity: 1, scale: 1 },
    motionTransition: { duration: 0.5, ease: 'easeOut' },
  },
  {
    id: 'popIn',
    name: 'Pop',
    category: 'skalieren',
    effectType: 'popIn',
    keyframes: [
      { offset: 0, properties: { opacity: 0, transform: 'scale(0.5)' } },
      { offset: 0.7, properties: { opacity: 1, transform: 'scale(1.05)' } },
      { offset: 1, properties: { opacity: 1, transform: 'scale(1)' } },
    ],
    defaultConfig: { duration: 0.4, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, scale: 0.5 },
    motionAnimate: { opacity: 1, scale: 1 },
    motionTransition: { duration: 0.4, type: 'spring', stiffness: 300, damping: 15 },
  },

  // === Zeichnen (für Edges) ===
  {
    id: 'drawLine',
    name: 'Linie zeichnen',
    category: 'zeichnen',
    effectType: 'drawLine',
    keyframes: [
      { offset: 0, properties: { 'stroke-dashoffset': 1000 } },
      { offset: 1, properties: { 'stroke-dashoffset': 0 } },
    ],
    defaultConfig: { duration: 1.0, delay: 0, easing: 'ease-in-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { pathLength: 0 },
    motionAnimate: { pathLength: 1 },
    motionTransition: { duration: 1.0, ease: 'easeInOut' },
  },
  {
    id: 'strokeDraw',
    name: 'Strich-Animation',
    category: 'zeichnen',
    effectType: 'strokeDraw',
    keyframes: [
      { offset: 0, properties: { 'stroke-dashoffset': 500, opacity: 0.3 } },
      { offset: 1, properties: { 'stroke-dashoffset': 0, opacity: 1 } },
    ],
    defaultConfig: { duration: 0.8, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { pathLength: 0, opacity: 0.3 },
    motionAnimate: { pathLength: 1, opacity: 1 },
    motionTransition: { duration: 0.8, ease: 'easeOut' },
  },
  {
    id: 'dashFlow',
    name: 'Gestrichelt fließen',
    category: 'zeichnen',
    effectType: 'dashFlow',
    keyframes: [
      { offset: 0, properties: { 'stroke-dashoffset': 24 } },
      { offset: 1, properties: { 'stroke-dashoffset': 0 } },
    ],
    defaultConfig: { duration: 0.6, delay: 0, easing: 'linear', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: { strokeDashoffset: 24 },
    motionAnimate: { strokeDashoffset: 0 },
    motionTransition: { duration: 0.6, ease: 'linear', repeat: Infinity },
  },

  // === Daten ===
  {
    id: 'countUp',
    name: 'Hochzählen',
    category: 'daten',
    effectType: 'countUp',
    keyframes: [
      { offset: 0, properties: { opacity: 0 } },
      { offset: 1, properties: { opacity: 1 } },
    ],
    defaultConfig: { duration: 1.0, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0 },
    motionAnimate: { opacity: 1 },
    motionTransition: { duration: 1.0 },
  },
  {
    id: 'growBar',
    name: 'Balken wachsen',
    category: 'daten',
    effectType: 'growBar',
    keyframes: [
      { offset: 0, properties: { transform: 'scaleY(0)', 'transform-origin': 'bottom' } },
      { offset: 1, properties: { transform: 'scaleY(1)', 'transform-origin': 'bottom' } },
    ],
    defaultConfig: { duration: 0.8, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { scaleY: 0, originY: 1 },
    motionAnimate: { scaleY: 1 },
    motionTransition: { duration: 0.8, ease: 'easeOut' },
  },

  // === Effekte ===
  {
    id: 'pulse',
    name: 'Pulsieren',
    category: 'effekte',
    effectType: 'pulse',
    keyframes: [
      { offset: 0, properties: { transform: 'scale(1)', opacity: 1 } },
      { offset: 0.5, properties: { transform: 'scale(1.05)', opacity: 0.8 } },
      { offset: 1, properties: { transform: 'scale(1)', opacity: 1 } },
    ],
    defaultConfig: { duration: 2.0, delay: 0, easing: 'ease-in-out', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: {},
    motionAnimate: { scale: [1, 1.05, 1], opacity: [1, 0.8, 1] },
    motionTransition: { duration: 2.0, repeat: Infinity, ease: 'easeInOut' },
  },
  {
    id: 'clipReveal',
    name: 'Clip Reveal',
    category: 'bewegen',
    effectType: 'clipReveal',
    keyframes: [
      { offset: 0, properties: { opacity: 0, 'clip-path': 'inset(20% 0 0 0)', transform: 'translateY(20px)' } },
      { offset: 1, properties: { opacity: 1, 'clip-path': 'inset(0 0 0 0)', transform: 'translateY(0)' } },
    ],
    defaultConfig: { duration: 0.7, delay: 0, easing: 'ease-out', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { opacity: 0, y: 20, clipPath: 'inset(20% 0 0 0)' },
    motionAnimate: { opacity: 1, y: 0, clipPath: 'inset(0 0 0 0)' },
    motionTransition: { duration: 0.7, ease: 'easeOut' },
  },
  {
    id: 'glowBorder',
    name: 'Glow Border',
    category: 'effekte',
    effectType: 'glowBorder',
    keyframes: [
      { offset: 0, properties: { '--angle': '0deg' } },
      { offset: 1, properties: { '--angle': '360deg' } },
    ],
    defaultConfig: { duration: 3.0, delay: 0, easing: 'linear', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: {},
    motionAnimate: {},
    motionTransition: { duration: 3.0, ease: 'linear', repeat: Infinity },
  },
  {
    id: 'shimmer',
    name: 'Shimmer',
    category: 'effekte',
    effectType: 'shimmer',
    keyframes: [
      { offset: 0, properties: { 'background-position': '-200% 0' } },
      { offset: 1, properties: { 'background-position': '200% 0' } },
    ],
    defaultConfig: { duration: 2.0, delay: 0, easing: 'ease-in-out', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: {},
    motionAnimate: {},
    motionTransition: { duration: 2.0, ease: 'easeInOut', repeat: Infinity },
  },
  {
    id: 'gradientText',
    name: 'Gradient Text',
    category: 'effekte',
    effectType: 'gradientText',
    keyframes: [
      { offset: 0, properties: { 'background-position': '0% center' } },
      { offset: 1, properties: { 'background-position': '200% center' } },
    ],
    defaultConfig: { duration: 3.0, delay: 0, easing: 'linear', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: {},
    motionAnimate: {},
    motionTransition: { duration: 3.0, ease: 'linear', repeat: Infinity },
  },
  {
    id: 'glowPulse',
    name: 'Glow Pulsieren',
    category: 'zeichnen',
    effectType: 'glowPulse',
    keyframes: [
      { offset: 0, properties: { opacity: 0.1 } },
      { offset: 0.5, properties: { opacity: 0.5 } },
      { offset: 1, properties: { opacity: 0.1 } },
    ],
    defaultConfig: { duration: 2.0, delay: 0, easing: 'ease-in-out', trigger: 'onLoad', iterationCount: 'infinite', fillMode: 'none' },
    motionInitial: { opacity: 0.1 },
    motionAnimate: { opacity: [0.1, 0.5, 0.1] },
    motionTransition: { duration: 2.0, repeat: Infinity, ease: 'easeInOut' },
  },
  {
    id: 'typewriter',
    name: 'Schreibmaschine',
    category: 'effekte',
    effectType: 'typewriter',
    keyframes: [
      { offset: 0, properties: { width: '0', overflow: 'hidden', 'white-space': 'nowrap' } },
      { offset: 1, properties: { width: '100%', overflow: 'hidden', 'white-space': 'nowrap' } },
    ],
    defaultConfig: { duration: 1.5, delay: 0, easing: 'steps(20, end)', trigger: 'onLoad', iterationCount: 1, fillMode: 'both' },
    motionInitial: { width: 0, overflow: 'hidden' },
    motionAnimate: { width: '100%' },
    motionTransition: { duration: 1.5, ease: 'linear' },
  },
];

export const PRESET_CATEGORIES: { id: string; label: string }[] = [
  { id: 'einblenden', label: 'Einblenden' },
  { id: 'bewegen', label: 'Bewegen' },
  { id: 'skalieren', label: 'Skalieren' },
  { id: 'zeichnen', label: 'Zeichnen' },
  { id: 'daten', label: 'Daten' },
  { id: 'effekte', label: 'Effekte' },
];
